accounts/urls.py
from django.urls import include, path


urlpatterns = [
	path('', include('django.contrib.auth.urls')),
]

rehersal_room/urls.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.urls import include, path


urlpatterns = [
	path('', include('reservation.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

reservation/urls.py
from django.urls import include, path

from .models import Comment, Event
from .views import EventListView, EventCreate, EventDelete


app_name = 'reservation'

urlpatterns = [
	path('', EventListView.as_view(), name='event-list'),
	path('<int:week>/', EventListView.as_view(), name='event-list'),
	path('create/', EventCreate.as_view(), name='event-create'),
	path('delete/<pk>/', EventDelete.as_view(), name='event-delete'),
]

reservation/models.py
from django.contrib.auth.models import User

from django.db import models

from datetime import date

class Event(models.Model):
	title = models.CharField(max_length=16, default='Próba')
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
	date = models.DateField(default=date.today)
	start_time = models.TimeField(default='11:00')
	end_time = models.TimeField(default='21:30')
	description = models.CharField(max_length=128, blank=True, null=True)
	is_periodic = models.BooleanField(default=False)

	def __str__(self):
		return f"{self.title} ({self.date}) of {self.author}"


class Comment(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE) 
	event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='comments') 
	content = models.CharField(max_length=128)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.author} commented {self.event} at {self.created_at.strftime('%Y-%m-%d %H:%M')}"

reservation/forms.py
import datetime as dt

from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Event


class EventCreateForm(ModelForm):
	class Meta:
		model = Event
		fields = ['title', 'date', 'start_time', 'end_time',  'description']

	def clean(self):
		cleaned_data = super().clean()
		end_time = cleaned_data.get("end_time")
		start_time = cleaned_data.get("start_time")
		date = cleaned_data.get("date")

		if all((date, start_time, end_time)): # Validate only if datetime fields are correct

			if end_time.hour == 21 and end_time.minute > 30:
				msg = "21:30 to max"
				self.add_error('end_time', msg)
			if end_time.hour >= 22 :
				msg = "21:30 to max"
				self.add_error('end_time', msg)
			if start_time.hour <= 10 :
				msg = "11:00 to min"
				self.add_error('start_time', msg)

			if start_time >= end_time:
				msg = "Start time nie może być większy niż End time"
				self.add_error('start_time', msg)
		
			same_day_events = Event.objects.filter(date=date).filter(start_time__gte=start_time).filter(end_time__lte=end_time)
			if same_day_events:
				msg = "Jest już zajęte"
				self.add_error('date', msg)

reservation/views.py
import datetime as dt

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from reservation.models import Event
from .forms import EventCreateForm


class EventListView(ListView):
	model = Event

	def get_queryset(self):

		def week_range(week_delta=0):
		    date = dt.date.today()
		    while date.weekday() != 0: # while date is not monday
		        date -= dt.timedelta(1)
		    return date + (dt.timedelta(7) * week_delta), date + dt.timedelta(7) + (dt.timedelta(7) * week_delta)

		if 'week' in self.kwargs:
			self.week=self.kwargs['week']
		else:
			self.week=0
		self.start, self.end = week_range(self.week)
		return Event.objects.filter(date__range=[self.start, self.end]).order_by('date', 'start_time')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['WEEKDAYS'] = ['Monday','Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
		context['week'] = self.week
		return context


class EventCreate(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventCreateForm
    success_url = reverse_lazy('reservation:event-list')
    login_url = 'accounts/login/'

    def form_valid(self, form):
    	form.instance.author = self.request.user
    	return super().form_valid(form)


class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('reservation:event-list')

    def dispatch(self, request, *args, **kwargs):
    	event=self.get_object()
    	if not request.user == event.author:
    		raise Exception('PERMISSION ERROR')
    	return super().dispatch(request, *args, **kwargs)

reservation/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Rehersal room</title>
  </head>
  <body>

  		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand px-4" href="{% url 'reservation:event-list' %}">DK100 Rehersal Room </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'reservation:event-list' %}">Calendar<span class="sr-only"></span></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'reservation:event-create' %}">New Reservation</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">New Reservation</a>
      </li>
      {% endif %}
    </ul>
  </div>
   {% if user.is_authenticated %}
      <p class="text-white bg-dark px-3">user: <strong>{{ user }}</strong></p>
   {% endif %}
</nav>
    <div class='container'>
    	     
    <br>
    {% block content %}{% endblock %}
	</div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
	</div>
  </body>
</html>

reservation/templates/reservation/event_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p class=>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" class="btn btn-danger">
</form>

{% endblock %}

reservation/templates/reservation/event_form.html
{% extends "base.html" %}

{% block content %}
 <h1 class='text-center'>New Reservation</h1>
<form method="post">{% csrf_token %}
 {{ form.as_p }}
 <input type="submit" value="Save" class="btn btn-dark">
</form>


{% endblock %}

reservation/templates/reservation/event_list.html
{% extends "base.html" %}

{% block content %}


 <h1 class='text-center'>Calendar</h1>

<ul class="nav justify-content-center">
  <li class="nav-item ">
   <a class="nav-link" href="{% url 'reservation:event-list' 0 %}">THIS WEEK</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'reservation:event-list' week|add:1 %}">NEXT WEEK</a>
  </li>
</ul>

<div class="table-responsive">
<table class="table table-bordered table table-striped">
  <thead>
  	<tr>
{% for day in WEEKDAYS %}
 		<th style="width:14%" class='text-center bg-light'>{{ day }}</th>
{% endfor %}
	</tr>
 </thead>
  <tbody>
  	 <tr>
	{% for day in WEEKDAYS %}
	<th style="width:14%">
	{% for event in object_list %}
{% if day == event.date|date:"l" %}

<div class="card bg-light mb-3  " style="max-width: 13rem;">
  <div class="card-header">
    <h6 class="card-title"><strong>{{ event.title }}</strong></h6>
    <h6><strong>{{ event.start_time|date:"G:i" }} - {{ event.end_time|date:"G:i"  }}</strong></h6></div>
  <div class="card-body bg-dark text-white">
    
  	<h5 class="card-title"> {{ event.date|date:"d.m.Y"  }}</h5>
    {% if event.description %}
     <cite title="Source Title">{{ event.description }}</cite>
    {% endif %}
    <p class="mt-3">
      <footer class="blockquote-footer">{{ event.author }}</footer>
    </p>
     {% if user.is_authenticated %}
      {% if user == event.author %}
     <a class="btn btn-danger" href="{% url 'reservation:event-delete' event.pk %}">ODWOŁAJ</a>
      {% endif %}
     {% endif %}

  </div>
</div>
{% endif %}

	{% endfor %}
	</th>
	{% endfor %}
	</tr>
  </tbody>
</table>
</div>







{% endblock %}